//https://github.com/nestjsx/crud/wiki/Requests#query-params

@baseurl = http://localhost:3000

GET {{baseurl}}/ HTTP/1.1

###

POST {{baseurl}}/parkingSpots HTTP/1.1
content-type: application/json

{
    "status": false,
    "latitude": "{{$randomInt -90 90}}", 
    "longitude": "{{$randomInt -180 180}}",
    "isForHandicap": false
}


###

POST {{baseurl}}/parkingSpots HTTP/1.1
content-type: application/json

{
    "status": false,
    "latitude": 7.94765, 
    "longitude": -5.24951,
    "isForHandicap": false
}

###

POST {{baseurl}}/parkingSpots HTTP/1.1
content-type: application/json

{
    "status": false,
    "latitude": 1.94765, 
    "longitude": 3.24951,
    "isForHandicap": false
}

###

DELETE {{baseurl}}/parkingSpots/1

###

POST {{baseurl}}/parkingSpots HTTP/1.1
content-type: application/json

{
    "status": false,
    "latitude": 5.30177, 
    "longitude": -15.09555,
    "isForHandicap": false
}

###

GET {{baseurl}}/parkingSpots/ HTTP/1.1

###

GET {{baseurl}}/parkingSpots/nearest/ HTTP/1.1

###

GET {{baseurl}}/parkingSpots/nearest?latitude=62.00021&longitude=33.00000 HTTP/1.1

###

GET {{baseurl}}/parkingSpots/10 HTTP/1.1


###

POST {{baseurl}}/users/ HTTP/1.1
content-type: application/json

{
    "firstName": "Corrado",
    "lastName": "Petrelli",
    "username": "corrado.petrelli",
    "password": "aldoaldoaldo",
    "balance": 100.2
}

### 
GET {{baseurl}}/users HTTP/1.1

###

DELETE {{baseurl}}/users?filter|| HTTP/1.1

###

GET {{baseurl}}/users?filter=balance||gt||100 HTTP/1.1


###
PUT {{baseurl}}/users/1/addToBalance HTTP/1.1
content-type: application/json

{
    "ciccio": 1
}